import { ReactNode } from "react";
import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";

import { Header } from "@/block";

import "./globals.css";
import "@/block/Header/Header.css";

const sourceSans = Source_Sans_3({ weight: ["300", "400", "500", "600", "700", "800", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
	return (
		<html lang="fr">
			<body className={sourceSans.className}>
				<Header />
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
