import { ReactNode } from "react";
import type { Metadata } from "next";

import { Header } from "@/block";

import "./globals.css";
import "@/block/Header/Header.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
	return (
		<html lang="fr">
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
